CHANGELOG, README.md, dbt_project.yml, integration_tests/dbt_project.yml, macros/utils/snowplow_delete_from_manifest.sql
Add the `snowplow_mobile_delete_from_manifest` macro to the list of supported macros, which is the `mobile` counterpart to the already existing `snowplow_web_delete_from_manifest` macro.
=> Add snowplow_mobile_delete_from_manifest macro (Close #54)

README.md, macros/utils/cross_db/datatypes.sql
- Add a type_string macro to generate a varchar type (Close #65)
- Add cross_db macro documentation (Close #67)
=> Add a type_string macro to generate a varchar type (Close #65)

macros/utils/cross_db/timestamp_functions.sql
Add support for Databricks runtimes below 10.4
=> Add support for Databricks runtimes below 10.4 (Close #85)

README.md, macros/utils/bigquery/combine_column_versions/combine_column_versions.sql, macros/utils/bigquery/combine_column_versions/exclude_column_versions.sql
Add the capability to exclude unwanted versions from the `combine_column_version` macro. 
We've encountered a need for this as we have introduced breaking changes to entity versions that cause BigQuery compilation errors when coalescing. For example, a change in field type across versions. This change allows for the avoidance of this by dropping known problematic versions out of the coalesce. 
This change makes the assumption that the column's version is always provided as the last 5 characters at the end of the column name (`column_X_X_X`).
To exclude version `1_0_0` from the coalescing: 
```sql
{%- set all_fields = snowplow_utils.combine_column_versions(
relation=ref('snowplow_web_base_events_this_run'),
column_prefix='product_v',
exclude_versions=['1_0_1'],
) -%}
select
{% for field in …
```
=> Exclude specific entity versions from combine_column_version macro

CHANGELOG, README.md, dbt_project.yml, integration_tests/dbt_project.yml, macros/utils/bigquery/combine_column_versions/combine_column_versions.sql, macros/utils/bigquery/combine_column_versions/exclude_column_versions.sql
Add the capability to exclude unwanted versions from the combine_column_version macro.
=> Release/snowplow utils/0.12.1

macros/incremental_hooks/get_incremental_manifest_status.sql, macros/incremental_hooks/return_base_new_event_limits.sql, macros/utils/return_limits_from_model.sql
If a user sets up a fresh installation of one of the dbt-snowplow packages then tries to execute `dbt compile` before `dbt run` they will get a compilation error as some macros try to to reference relations that do not yet exist. We can handle this by checking if the relation exists in these macros and if not we raise a warning and return empty strings instead.
- [NA] I have updated the README.md (if applicable)
- [NA] I have added tests & descriptions to my models (and macros if applicable)
- [NA] I have raised a [documentation](https://github.com/snowplow/documentation) PR if applicable (Link here if required)
=> Fix initial dbt compile error (Close #69)

dbt_project.yml, macros/materializations/base_incremental/common/get_merge_sql.sql, macros/materializations/snowplow_incremental/common/snowplow_validate_get_incremental_strategy.sql, macros/utils/cross_db/datatypes.sql
The current materialization is complex and out-dated, missing key new features that the dbt incremental method offers such as the `on_schema_change` flag, and more recently the incremental predicates. To add these features and to continue to support the materialization across 4+ warehouses is a large amount of work when compared to the relatively small difference our materialization offers over the default, i.e. the date filter on upserts.
Using the new incremental predicates we are able to generate the same date filter to be applied onto the merge statements, without having to copy the entire materialization. This requires an overwrite of the `dispatch` in the user's project yaml file.
1) The decision to overwrite the `default__get_merge_sql` and `default__get_delete_insert_merge_sql` …
=> Predicate incremental materialization

CHANGELOG, dbt_project.yml, integration_tests/dbt_project.yml, macros/incremental_hooks/get_incremental_manifest_status.sql, macros/utils/cross_db/get_string_agg.sql
This release does 2 things:
1) It adds the ability to add the package name that is calling the run limits to the message, which was a requested feature and will need porting into our other packages but this enables it.
2) It fixes a weird databricks bug that can happen when you try and array sort hundreds of nulls that leads to a java based error. I can't reliably reproduce it in the int tests without adding thousands of events so you'll have to take my word that it seems to consistently fix the issue by removing null-valued items from the sort first (these were removed by the array_join function later anyway so the result is the same). This should be more efficient and not cause the same issue.
I've done it in one big PR because it's was two tiny changes. None of these should be breaking …
=> Release/snowplow utils/0.14.3

integration_tests/dbt_project.yml, macros/base/base_create_snowplow_events_this_run.sql, macros/base/base_create_snowplow_sessions_lifecycle_manifest.sql
@agnessnowplow Raised an issue around when the session/user identifiers have the same context it fails on PG/RS (due to duplicate CTEs with the same name). This is actually a wider issue, it would fail with the same context used multiple times in one of the identifiers, and also if you use the context as an identifier then add it in the `entity_or_sde` as well. Giving each CTE a custom name felt complicated, so I have instead made the logic directly on the base macros.
Basically, I have got a distinct list of contexts that need CTEing and joining, and where there are duplicates it uses the alias and prefix of the _FIRST_ instance, but the _FIELD_ of the actual record (please double check I haven't misses this anywhere). I do not raise a warning in the manifest because they should never …
=> Fixes + check for dupes contexts in postgres/redshift

README.md, docs/markdown/snowplow_utils_macro_docs.md, integration_tests/dbt_project.yml, integration_tests/models/utils/cross_db/cross_db.yml, integration_tests/models/utils/cross_db/expected_get_field_bq.sql, integration_tests/models/utils/cross_db/test_get_field_bq.sql, macros/base/base_create_snowplow_events_this_run.sql, macros/base/base_create_snowplow_sessions_lifecycle_manifest.sql, macros/utils/cross_db/get_field.sql
Add multi-version support to get_field for bigquery, just checking for an _* and coalesce across those. Need to update the readme still.
=> Add multi-version support to get_field for bigquery

macros/base/base_create_snowplow_quarantined_sessions.sql
This is the issue discussed [here](https://discourse.snowplow.io/t/dbt-snowplow-web-0-16-0-package-fails-on-run-redshift/9090) with a fix provided by the user, although I was never able to reproduce it locally.. This causes an issue when used in a subquery in the lifecycle manifest table.
=> Fix issue with redshift 8001 error

macros/base/base_create_snowplow_events_this_run.sql
Fix an old reference for the default value of `session_identifiers` in the `base_create_snowplow_events_this_run` macro
=> Fix old reference

integration_tests/data/utils/data_app_id_filter.csv, integration_tests/models/utils/expected_app_id_filter.sql, integration_tests/models/utils/test_app_id_filter.sql, macros/utils/app_id_filter.sql
Allow `null` to be supplied in the app id filters list and process it correctly. Close #149
=> Allow null value in app_id filter list

.gitignore, CHANGELOG, docs/markdown/snowplow_utils_macro_docs.md, integration_tests/data/utils/data_parse_agg_dict.csv, integration_tests/models/utils/expected_parse_agg_dict.sql, integration_tests/models/utils/test_parse_agg_dict.sql, integration_tests/models/utils/utils.yml, macros/utils/parse_agg_dict.sql, macros/utils/schema.yml
Adds a parse_agg_dict macro to allow us to use it in downstream packages without having to re-implement it every time.
=> Add parse_agg_dict macro

CHANGELOG, macros/base/base_create_snowplow_sessions_lifecycle_manifest.sql
It's possible a user could provide a non-unique user identifier for a session via custom sql, this ensures we take the max as we do with non-custom sql
=> Add max clause around user identifier custom sql

integration_tests/models/utils/bigquery/data_combine_column_versions.sql, integration_tests/models/utils/bigquery/expected_combine_column_versions.sql, integration_tests/models/utils/bigquery/test_combine_column_versions.sql, macros/utils/bigquery/combine_column_versions/combine_column_versions.sql, macros/utils/bigquery/combine_column_versions/exclude_column_versions.sql
This PR fixes an issue where the exclude versions was limited to only 1 digit for each part of the version number.
https://snplow.atlassian.net/browse/PE-6264
=> Remove hardcoded limit of exclude versions length

CHANGELOG, dbt_project.yml, integration_tests/dbt_project.yml, integration_tests/models/utils/bigquery/data_combine_column_versions.sql, integration_tests/models/utils/bigquery/expected_combine_column_versions.sql, integration_tests/models/utils/bigquery/test_combine_column_versions.sql, macros/utils/bigquery/combine_column_versions/combine_column_versions.sql, macros/utils/bigquery/combine_column_versions/exclude_column_versions.sql
This PR releases the new version of utils, which contains a fix for the exclude column versions of longer sizes
https://snplow.atlassian.net/browse/PE-6264
https://snplow.atlassian.net/browse/BCPF-1089
https://www.notion.so/keep-in-the-snow/Utils-1ddfa63b23d84032b5ae63eda88f9f8f?pvs=4
Update https://snplow.atlassian.net/browse/BCPF-1089
=> Release/snowplow utils/0.16.4

CHANGELOG, dbt_project.yml, integration_tests/dbt_project.yml, integration_tests/models/utils/bigquery/data_combine_column_versions.sql, integration_tests/models/utils/bigquery/expected_combine_column_versions.sql, integration_tests/models/utils/bigquery/test_combine_column_versions.sql, integration_tests/models/utils/cross_db/cross_db.yml, macros/utils/bigquery/combine_column_versions/exclude_column_versions.sql
This release adds some functionality to the combine column versions requested by a customer.
https://www.notion.so/keep-in-the-snow/Utils-df148faf2eca4c1c9e098f46752f5f1e
https://snowplow.zendesk.com/agent/tickets/40331
=> Release/snowplow utils/0.16.7

README.md, macros/base/base_create_snowplow_events_this_run.sql, macros/base/base_create_snowplow_sessions_lifecycle_manifest.sql
Some of our trackers (e.g specific older versions of the AMP tracker or the Pixel tracker) do not send any value for `dvce_created_tstamp` and `dvce_sent_tstamp`. While the snowplow sessionization logic adds a filter to prevent potentially large table scans and reprocessing old sessions that are sent exceptionally late (e.g due to a bot) for such cases this should not matter as there is  no retry on those trackers: events are sent right after tracking them or not at all.
This PR allows for setting a variable to coalesce the value with `collector_tstamp`, which should be available in all trackers.
This should not be a breaking change as it is added as an optional parameter. So far it has been tested locally and in this Unified [PR](https://github.com/snowplow/dbt-snowplow-unified/pull/74).
=> Allow for allow_null_dvce_tstamps var

.github/workflows/pr_tests.yml, CHANGELOG, README.md, dbt_project.yml, integration_tests/dbt_project.yml, macros/base/base_create_snowplow_events_this_run.sql, macros/base/base_create_snowplow_sessions_lifecycle_manifest.sql, macros/incremental_hooks/apply_grants.sql
This release extends support for those users who would like to use the Snowplow incremental base macros but are using specific older versions of the AMP tracker or the Pixel tracker which do not send dvce_created / dvce_sent_tstamp fields. It also fixes a bug in the apply_grands() macro when the users does not have a grants config defined.
[](https://www.notion.so/keep-in-the-snow/5058060fa44841989620e4cd306404ca?v=86817f2dc72942c4aee757a0b6756202&p=9cc22e6c952c4c14a22c573531cf4d27&pm=s)
=> Release/snowplow utils/0.16.8

dbt_project.yml, integration_tests/models/utils/cross_db/cross_db.yml, macros/utils/return_limits_from_model.sql, macros/utils/schema.yml
https://snplow.atlassian.net/jira/software/c/projects/PE/boards/50?assignee=712020%3Ab916e641-2c6f-4de9-82f6-d175e2e15bee&selectedIssue=PE-6573
Updated the macro to stop an error message occurring when a specific scenario appears in the attribution model. 
This change modifies the macro adding a new argument. The argument is a boolean true or false which is an optional argument which automatically sets to false. If I change the argument is set to false the macro runs as it did previously, but when set to true instead of outputting a high date time stamp ('9999-01-01','999-01-02) it outputs ('0000-01-01','0000-01-02'.
note.
there was an issue with testing because of a dbt update which required me seeking some help from Agnes to change the version of testing's dbt. without the dbt vewrsion …
=> initial suggestion minor tests completed sucessfully

.github/workflows/pr_tests.yml, integration_tests/ci/profiles.yml, integration_tests/dbt_project.yml, macros/utils/get_schemas_by_pattern.sql, macros/utils/post_ci_cleanup.sql
=> Utils for Spark ( Iceberg ) Support RC2

.github/workflows/pr_tests.yml, macros/materializations/base_incremental/common/get_merge_sql.sql
`Snowflake` and `Postgres` Snowplow dbt package users who are using `delete+insert incremental strategy` from dbt v1.9.4 onwards (and are reliant on the snowplow optimize for incremental runs) will find errors starting in their `snowplow_base_session_lifecycle_manifest` tables due to a recent dbt [change](https://github.com/dbt-labs/dbt-adapters/pull/910) in the original macro we extend/overwrite. This PR aims at fixing that issue while maintaining backwards compatibility.
I'm also allowing for the latest dbt version to pass through for the integration tests as they seem to have been fixed due to python compatibility.
=> Fix broken delete insert override for new dbt versions

.github/workflows/pr_tests.yml, CHANGELOG, dbt_project.yml, integration_tests/dbt_project.yml, macros/materializations/base_incremental/common/get_merge_sql.sql
`Snowflake` and `Postgres` Snowplow dbt package users who are using `delete+insert incremental strategy` from dbt v1.9.4 onwards (and are reliant on the snowplow optimize for incremental runs) will find errors starting in their `snowplow_base_session_lifecycle_manifest` tables due to a recent dbt [change](https://github.com/dbt-labs/dbt-adapters/pull/910) in the original macro we extend/overwrite. This PR aims at fixing that issue while maintaining backwards compatibility.
I'm also allowing for the latest dbt version to pass through for the integration tests as they seem to have been fixed due to python compatibility.
=> Release/snowplow utils/0.17.2
