- .github/workflows/pr_tests.yml
- CHANGELOG
- README.md
- dbt_project.yml
- integration_tests/dbt_project.yml
- packages.yml
> Release/snowplow utils/0.7.0

- CHANGELOG
- README.md
- dbt_project.yml
- integration_tests/dbt_project.yml
- macros/utils/cross_db/datatypes.sql
Add a type_string macro to generate a varchar type (Close #65)
Add cross_db macro documentation (Close #66)
> Release/snowplow utils/0.8.0

- README.md
- macros/utils/set_query_tag.sql
- Add `set_query_tag` functionality (Close #71)
> Add `set_query_tag` functionality (Close #71)

- .github/CODEOWNERS
- CHANGELOG
- README.md
- dbt_project.yml
- integration_tests/dbt_project.yml
- macros/utils/set_query_tag.sql
> Release/snowplow utils/0.9.0

- .github/workflows/pr_tests.yml
- integration_tests/.scripts/integration_tests.sh
- integration_tests/ci/profiles.yml
- integration_tests/dbt_project.yml
- macros/materializations/snowplow_incremental/common/get_snowplow_upsert_limits_sql.sql
- macros/materializations/snowplow_incremental/common/snowplow_merge.sql
- macros/materializations/snowplow_incremental/spark/snowplow_incremental.sql
- macros/utils/cross_db/timestamp_functions.sql
- macros/utils/get_partition_by.sql
- macros/utils/get_schemas_by_pattern.sql
- macros/utils/post_ci_cleanup.sql
- macros/utils/snowplow_delete_from_manifest.sql
> Add support for Databricks via the Spark connector (Close #80)

- .github/workflows/pr_tests.yml
- CHANGELOG
- README.md
- dbt_project.yml
- integration_tests/.scripts/integration_tests.sh
- integration_tests/ci/profiles.yml
- integration_tests/dbt_project.yml
- macros/materializations/snowplow_incremental/common/get_snowplow_upsert_limits_sql.sql
- macros/materializations/snowplow_incremental/common/snowplow_merge.sql
- macros/materializations/snowplow_incremental/spark/snowplow_incremental.sql
- macros/utils/cross_db/timestamp_functions.sql
- macros/utils/get_partition_by.sql
- macros/utils/get_schemas_by_pattern.sql
- macros/utils/post_ci_cleanup.sql
- macros/utils/snowplow_delete_from_manifest.sql
Add support for Databricks via Spark (Close #80)
> Release/snowplow utils/0.11.0

- macros/materializations/snowplow_incremental/default/snowplow_incremental.sql
Add ability to create indexes from config (Close #83)
> Add ability to create indexes from config (Close #83)

- CHANGELOG
- dbt_project.yml
- integration_tests/dbt_project.yml
- macros/materializations/snowplow_incremental/default/snowplow_incremental.sql
- macros/utils/cross_db/timestamp_functions.sql
Add ability to create indexes from config (Close #83)
Add support for Databricks runtimes below 10.4 (Close #85)
> Release/snowplow utils/0.12.0

- integration_tests/models/materializations/default_strategy/test_snowplow_incremental.sql
- integration_tests/models/materializations/default_strategy/test_snowplow_incremental_w_lookback_disabled.sql
- packages.yml
Bump `dbt-utils` version for patch fix
> Bump `dbt-utils` version for patch fix (Close #92)

- CHANGELOG
- dbt_project.yml
- integration_tests/dbt_project.yml
- integration_tests/models/materializations/default_strategy/test_snowplow_incremental.sql
- integration_tests/models/materializations/default_strategy/test_snowplow_incremental_w_lookback_disabled.sql
- macros/materializations/snowplow_incremental/common/snowplow_validate_get_incremental_strategy.sql
- packages.yml
> Release/snowplow utils/0.12.2

- CHANGELOG
- README.md
- dbt_project.yml
- integration_tests/dbt_project.yml
- integration_tests/models/utils/data_get_string_agg.sql
- integration_tests/models/utils/data_get_string_agg_int.sql
- integration_tests/models/utils/data_get_string_agg_int_string.sql
- integration_tests/models/utils/expected_get_string_agg.sql
- integration_tests/models/utils/expected_get_string_agg_int.sql
- integration_tests/models/utils/expected_get_string_agg_int_string.sql
- integration_tests/models/utils/test_get_string_agg.sql
- integration_tests/models/utils/test_get_string_agg_int.sql
- integration_tests/models/utils/test_get_string_agg_int_string.sql
- integration_tests/models/utils/utils.yml
- macros/utils/bigquery/get_optional_fields.sql
- macros/utils/cross_db/get_split_to_array.sql
- macros/utils/cross_db/get_string_agg.sql
- macros/utils/cross_db/unnest.sql
Add unnest macro #99
Add Media Player macros #79
> Release/snowplow utils/0.12.3

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/labels.yml
- .github/pull_request_template.md
- .github/workflows/no-response.yml
- .github/workflows/pr_tests.yml
- .github/workflows/release.yml
- .github/workflows/set-labels.yml
- .github/workflows/triage-labeler.yml
- integration_tests/ci/profiles.yml
Add the release action and the other standard labels and actions we have across repos
> Add standard actions and templates

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/labels.yml
- .github/pull_request_template.md
- .github/workflows/no-response.yml
- .github/workflows/pr_tests.yml
- .github/workflows/release.yml
- .github/workflows/set-labels.yml
- .github/workflows/triage-labeler.yml
- CHANGELOG
- README.md
- dbt_project.yml
- integration_tests/ci/profiles.yml
- integration_tests/dbt_project.yml
- macros/incremental_hooks/get_run_limits.sql
- macros/materializations/snowplow_incremental/common/get_snowplow_upsert_limits_sql.sql
- macros/utils/cross_db/timestamp_functions.sql
- macros/utils/cross_db/unnest.sql
- packages.yml
> Release/snowplow utils/0.13.0

- .github/workflows/publish-gh-pages.yml
Utils has no models, so needs a simpler gh pages generation script.
> fix utils gh pages generation

- .github/pull_request_template.md
- .github/workflows/publish-gh-pages.yml
- CHANGELOG
- dbt_project.yml
- integration_tests/dbt_project.yml
- macros/incremental_hooks/get_incremental_manifest_status.sql
- macros/incremental_hooks/return_base_new_event_limits.sql
- macros/utils/return_limits_from_model.sql
This release fixes a compilation error raised if dbt compile is ran on a fresh installation of one of the dbt-snowplow packages. Under the hood we also fix the GitHub pages generation automation and update the pr template.
Fix initial dbt compile error (Close #69)
Fix utils gh pages generation
Update pr template
> Release/snowplow utils/0.13.2

- .github/workflows/publish-gh-pages.yml
- CHANGELOG
- dbt_project.yml
- integration_tests/dbt_project.yml
- macros/materializations/base_incremental/common/get_merge_sql.sql
- macros/materializations/snowplow_incremental/common/snowplow_validate_get_incremental_strategy.sql
- macros/utils/cross_db/datatypes.sql
Release candidate 1 for the new materialization, due to release on monday.
> Release/snowplow utils/0.14.0rc1

- integration_tests/dbt_project.yml
- integration_tests/models/base/actual/snowplow_base_events_this_run_actual.sql
- integration_tests/models/base/actual/snowplow_base_sessions_lifecycle_manifest_actual.sql
- integration_tests/models/base/source/databricks/snowplow_events_stg.sql
- integration_tests/models/base/source/snowflake/snowplow_events_stg.sql
Update int test contexts for non-bq targets
> Update int test contexts for non-bq targets

- macros/base/base_create_snowplow_events_this_run.sql
- macros/base/base_create_snowplow_sessions_lifecycle_manifest.sql
- macros/incremental_hooks/get_enabled_snowplow_models.sql
- macros/incremental_hooks/get_run_limits.sql
- macros/utils/bigquery/combine_column_versions/flatten_fields.sql
- macros/utils/bigquery/combine_column_versions/merge_fields_across_col_versions.sql
- macros/utils/cross_db/get_array_to_string.sql
- macros/utils/cross_db/get_field.sql
- macros/utils/cross_db/get_split_to_array.sql
- macros/utils/cross_db/get_string_agg.sql
- macros/utils/cross_db/timestamp_functions.sql
- macros/utils/cross_db/unnest.sql
Remove red rainbows from indentation
> Fix indentation

- macros/base/base_create_snowplow_sessions_lifecycle_manifest.sql
> Update error message when no user identifier is present

- CHANGELOG
- dbt_project.yml
- integration_tests/dbt_project.yml
- macros/base/base_create_snowplow_events_this_run.sql
> Release/snowplow utils/0.15.2

- CHANGELOG
- dbt_project.yml
- integration_tests/dbt_project.yml
- macros/utils/cross_db/unnest.sql
> Release/snowplow utils/0.16.1

- .github/pull_request_template.md
- .gitignore
- CHANGELOG
- dbt_project.yml
- docs/markdown/snowplow_utils_macro_docs.md
- integration_tests/data/utils/data_app_id_filter.csv
- integration_tests/data/utils/data_parse_agg_dict.csv
- integration_tests/dbt_project.yml
- integration_tests/models/utils/expected_app_id_filter.sql
- integration_tests/models/utils/expected_parse_agg_dict.sql
- integration_tests/models/utils/test_app_id_filter.sql
- integration_tests/models/utils/test_parse_agg_dict.sql
- integration_tests/models/utils/utils.yml
- macros/base/base_create_snowplow_sessions_lifecycle_manifest.sql
- macros/incremental_hooks/apply_grants.sql
- macros/utils/app_id_filter.sql
- macros/utils/parse_agg_dict.sql
- macros/utils/schema.yml
This release adds the new parge_agg_dicty, adds table grants by variable, and fixes a potential issue with custom sql user identifiers
> Release/snowplow utils/0.16.2

- CHANGELOG
- dbt_project.yml
- integration_tests/dbt_project.yml
- macros/base/base_create_snowplow_events_this_run.sql
This PR allows the use of context/sdes in the custom SQL part of events this run. It's also moved for non-redshift for consistency.
https://www.notion.so/keep-in-the-snow/Utils-9fda179b89884493bb1f01a2cce0fc87
https://snplow.atlassian.net/browse/BCPF-1157
> Release/snowplow utils/0.16.5

- .github/workflows/publish-gh-pages.yml
> Disable upgrade in workflow

- macros/utils/post_ci_cleanup.sql
We need to update in order not to delete the schema in spark, as the schema plays the role of the database
> Update post_ci_cleanup macro for spark

- macros/base/base_create_snowplow_events_this_run.sql
Bug fix for spark, reading the whole event table when is not needed
> Work on base_create_snowplow_events_this_run model

- CHANGELOG
- dbt_project.yml
- integration_tests/dbt_project.yml
- macros/base/base_create_snowplow_events_this_run.sql
This release is aiming to optimise base_create_snowplow_events_this_run macro for spark.
- We moved the order of some calculation to help with the query optimization.
- [] ✅ Test
> Release/snowplow utils/0.17.1

- macros/incrementalize/incrementalize_by_tstamp/create_daily_manifest.sql
- macros/incrementalize/incrementalize_by_tstamp/get_dates_to_process.sql
Quick fixes to support renamed models.
> Fixes due to renaming

- macros/utils/license_check.sql
This pull request introduces a new macro to enforce license compliance for Snowplow Analytics.
1. The macro checks whether the user has accepted the Snowplow License terms before proceeding.
2. This macro will be called by Snowplow dbt packages (e.g. ecommerce, unified etc) to enforce the check.
Mechanics of operation:
* [`macros/utils/license_check.sql`](diffhunk://#diff-490795b2070ccdd69b2e9c61c968bc696c205905f511159e4d6b44693a1d7ee2R1-R18): Added a new `license_check` macro that raises an error if the `snowplow__license_accepted` variable in `dbt_project.yml` is not set to `true`. This ensures users explicitly accept the Snowplow License before using a Snowplow dbt package.
> Feature/aisp 514/utils license acceptance check

- CHANGELOG
- dbt_project.yml
- integration_tests/dbt_project.yml
- macros/utils/license_check.sql
Introduces the macro `license_check` for use by snowplow dbt repos to validate user license acceptance.
> Release/snowplow utils/0.17.3
